//ES CUANDO LAS VARIABLES Y LAS FUNCIONES SE DECLARAN ANTES DE QUE SE PROCESE CUALQUIER TIPO DE CODIGO.
//EL HOISTING YA NO SUCEDE A PARTIR DE ECMAScript 6

console.log(nombre)
var nombre = "Zaier";



