//EXISTEN DOS TIPOS DE SCOPES

//SCOPE GLOBAL Y SCOPE LOCAL

//EL GLOBAL ES DONDE SE DECLARA TODAS LAS VARIABLES, TODAS LAS FUNCIONES Y TODO LO QUE ESCRIBAMOS.

//EL SCOPE LOCAL ES CUANDO INICIALIZAMOS UNA FUNCION, ES IMPORTANTE RECALCAR QUE ES SCOPE LOCAL PUEDE ACCEDER AL SCOPE GLOBAL, PERO EL GLOBAL NO PUEDE ACCEDER AL LOCAL.

var nombre = "Zaier";

function fun(){
    var apellido = "Vera";
    return nombre + " " + apellido
}

fun()

//"Zaier Vera"

